apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geocentric-model-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jimliu9527/ArgoCD_test.git
    targetRevision: HEAD
    path: ./declarative/manifests/geocentric-model
   
  destination:
    server: https://kubernetes.default.svc
    namespace: geocentric-model

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
  postSync:
      - name: run-post-sync-job
        command: ["/bin/bash", "-c"]
        args: ["kubectl apply -f ./declarative/manifests/geocentric-model/post-sync-job.yml"]