apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geocentric-model-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jimliu9527/ArgoCD_test.git
    targetRevision: HEAD
    path: ./declarative/manifests/geocentric-model
   
  destination:
    server: https://kubernetes.default.svc
    namespace: geocentric-model

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
---
apiVersion: batch/v1
kind: Job
metadata:
  name: regression-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: post-sync-container
        image: jimliu9527/playwright-cloud-filtering:v1
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["sleep 180; npm run stg; npx http-server ./playwright-report -p 8080"]
      restartPolicy: Never
  backoffLimit: 0